//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_PPE3_CLIENT.MyWS_Ref {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_Mission", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_Mission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MissionField;
        
        private int PersonneField;
        
        private int Note_de_fraisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_MissionField;
        
        private System.DateTime date_missionField;
        
        private int persone_selectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Mission {
            get {
                return this.MissionField;
            }
            set {
                if ((this.MissionField.Equals(value) != true)) {
                    this.MissionField = value;
                    this.RaisePropertyChanged("Mission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Personne {
            get {
                return this.PersonneField;
            }
            set {
                if ((this.PersonneField.Equals(value) != true)) {
                    this.PersonneField = value;
                    this.RaisePropertyChanged("Personne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Note_de_frais {
            get {
                return this.Note_de_fraisField;
            }
            set {
                if ((this.Note_de_fraisField.Equals(value) != true)) {
                    this.Note_de_fraisField = value;
                    this.RaisePropertyChanged("Note_de_frais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nom_Mission {
            get {
                return this.Nom_MissionField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_MissionField, value) != true)) {
                    this.Nom_MissionField = value;
                    this.RaisePropertyChanged("Nom_Mission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime date_mission {
            get {
                return this.date_missionField;
            }
            set {
                if ((this.date_missionField.Equals(value) != true)) {
                    this.date_missionField = value;
                    this.RaisePropertyChanged("date_mission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int persone_select {
            get {
                return this.persone_selectField;
            }
            set {
                if ((this.persone_selectField.Equals(value) != true)) {
                    this.persone_selectField = value;
                    this.RaisePropertyChanged("persone_select");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_PERSONNEL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_PERSONNEL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int id_persoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MATRICULEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRENOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUEField;
        
        private int CPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VILLEField;
        
        private System.DateTime DATE_D_EMBAUCHEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        private int isadminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_perso {
            get {
                return this.id_persoField;
            }
            set {
                if ((this.id_persoField.Equals(value) != true)) {
                    this.id_persoField = value;
                    this.RaisePropertyChanged("id_perso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MATRICULE {
            get {
                return this.MATRICULEField;
            }
            set {
                if ((object.ReferenceEquals(this.MATRICULEField, value) != true)) {
                    this.MATRICULEField = value;
                    this.RaisePropertyChanged("MATRICULE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NOM {
            get {
                return this.NOMField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMField, value) != true)) {
                    this.NOMField = value;
                    this.RaisePropertyChanged("NOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PRENOM {
            get {
                return this.PRENOMField;
            }
            set {
                if ((object.ReferenceEquals(this.PRENOMField, value) != true)) {
                    this.PRENOMField = value;
                    this.RaisePropertyChanged("PRENOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RUE {
            get {
                return this.RUEField;
            }
            set {
                if ((object.ReferenceEquals(this.RUEField, value) != true)) {
                    this.RUEField = value;
                    this.RaisePropertyChanged("RUE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CP {
            get {
                return this.CPField;
            }
            set {
                if ((this.CPField.Equals(value) != true)) {
                    this.CPField = value;
                    this.RaisePropertyChanged("CP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string VILLE {
            get {
                return this.VILLEField;
            }
            set {
                if ((object.ReferenceEquals(this.VILLEField, value) != true)) {
                    this.VILLEField = value;
                    this.RaisePropertyChanged("VILLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime DATE_D_EMBAUCHE {
            get {
                return this.DATE_D_EMBAUCHEField;
            }
            set {
                if ((this.DATE_D_EMBAUCHEField.Equals(value) != true)) {
                    this.DATE_D_EMBAUCHEField = value;
                    this.RaisePropertyChanged("DATE_D_EMBAUCHE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int isadmin {
            get {
                return this.isadminField;
            }
            set {
                if ((this.isadminField.Equals(value) != true)) {
                    this.isadminField = value;
                    this.RaisePropertyChanged("isadmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_Note_Frais", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_Note_Frais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int id_note_fraisField;
        
        private System.DateTime date_depotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_noteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_note_frais {
            get {
                return this.id_note_fraisField;
            }
            set {
                if ((this.id_note_fraisField.Equals(value) != true)) {
                    this.id_note_fraisField = value;
                    this.RaisePropertyChanged("id_note_frais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime date_depot {
            get {
                return this.date_depotField;
            }
            set {
                if ((this.date_depotField.Equals(value) != true)) {
                    this.date_depotField = value;
                    this.RaisePropertyChanged("date_depot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nom_note {
            get {
                return this.nom_noteField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_noteField, value) != true)) {
                    this.nom_noteField = value;
                    this.RaisePropertyChanged("nom_note");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_Liste_Frais", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_Liste_Frais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int id_ligne_fraisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_ligneField;
        
        private int totalField;
        
        private int donnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_ligne_frais {
            get {
                return this.id_ligne_fraisField;
            }
            set {
                if ((this.id_ligne_fraisField.Equals(value) != true)) {
                    this.id_ligne_fraisField = value;
                    this.RaisePropertyChanged("id_ligne_frais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nom_ligne {
            get {
                return this.nom_ligneField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_ligneField, value) != true)) {
                    this.nom_ligneField = value;
                    this.RaisePropertyChanged("nom_ligne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int donner {
            get {
                return this.donnerField;
            }
            set {
                if ((this.donnerField.Equals(value) != true)) {
                    this.donnerField = value;
                    this.RaisePropertyChanged("donner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWS_Ref.MyWSSoap")]
    public interface MyWSSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément Liste_MissionResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Liste_Mission", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionResponse Liste_Mission(WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Liste_Mission", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionResponse> Liste_MissionAsync(WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément Liste_PersonnelResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Liste_Personnel", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelResponse Liste_Personnel(WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Liste_Personnel", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelResponse> Liste_PersonnelAsync(WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_NOM de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Missions_By_Name_User", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserResponse Missions_By_Name_User(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Missions_By_Name_User", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserResponse> Missions_By_Name_UserAsync(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_MATRICULE de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Personnel", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelResponse Insert_Personnel(WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Personnel", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelResponse> Insert_PersonnelAsync(WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_personne de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Missions_By_Id_User", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserResponse Missions_By_Id_User(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Missions_By_Id_User", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserResponse> Missions_By_Id_UserAsync(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Je_Me_Connecte", ReplyAction="*")]
        bool Je_Me_Connecte();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Je_Me_Connecte", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Je_Me_ConnecteAsync();
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_MATRICULE de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Personnel", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelResponse Update_Personnel(WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Personnel", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelResponse> Update_PersonnelAsync(WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_user de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_user", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.Delete_userResponse Delete_user(WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_user", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Delete_userResponse> Delete_userAsync(WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_mission", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.insert_missionResponse insert_mission(WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_mission", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.insert_missionResponse> insert_missionAsync(WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément DATE_DEPOT de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_Frais", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.insert_FraisResponse insert_Frais(WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_Frais", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.insert_FraisResponse> insert_FraisAsync(WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_ligne_Frais", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisResponse insert_ligne_Frais(WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_ligne_Frais", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisResponse> insert_ligne_FraisAsync(WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément List_note_fraisResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List_note_frais", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisResponse List_note_frais(WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List_note_frais", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisResponse> List_note_fraisAsync(WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément list_ligne_fraisResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/list_ligne_frais", ReplyAction="*")]
        WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisResponse list_ligne_frais(WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/list_ligne_frais", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisResponse> list_ligne_fraisAsync(WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Liste_MissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Liste_Mission", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequestBody Body;
        
        public Liste_MissionRequest() {
        }
        
        public Liste_MissionRequest(WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Liste_MissionRequestBody {
        
        public Liste_MissionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Liste_MissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Liste_MissionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionResponseBody Body;
        
        public Liste_MissionResponse() {
        }
        
        public Liste_MissionResponse(WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Liste_MissionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.C_Mission[] Liste_MissionResult;
        
        public Liste_MissionResponseBody() {
        }
        
        public Liste_MissionResponseBody(WS_PPE3_CLIENT.MyWS_Ref.C_Mission[] Liste_MissionResult) {
            this.Liste_MissionResult = Liste_MissionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Liste_PersonnelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Liste_Personnel", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequestBody Body;
        
        public Liste_PersonnelRequest() {
        }
        
        public Liste_PersonnelRequest(WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Liste_PersonnelRequestBody {
        
        public Liste_PersonnelRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Liste_PersonnelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Liste_PersonnelResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelResponseBody Body;
        
        public Liste_PersonnelResponse() {
        }
        
        public Liste_PersonnelResponse(WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Liste_PersonnelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.C_PERSONNEL[] Liste_PersonnelResult;
        
        public Liste_PersonnelResponseBody() {
        }
        
        public Liste_PersonnelResponseBody(WS_PPE3_CLIENT.MyWS_Ref.C_PERSONNEL[] Liste_PersonnelResult) {
            this.Liste_PersonnelResult = Liste_PersonnelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Missions_By_Name_UserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Missions_By_Name_User", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequestBody Body;
        
        public Missions_By_Name_UserRequest() {
        }
        
        public Missions_By_Name_UserRequest(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Missions_By_Name_UserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_NOM;
        
        public Missions_By_Name_UserRequestBody() {
        }
        
        public Missions_By_Name_UserRequestBody(string P_NOM) {
            this.P_NOM = P_NOM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Missions_By_Name_UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Missions_By_Name_UserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserResponseBody Body;
        
        public Missions_By_Name_UserResponse() {
        }
        
        public Missions_By_Name_UserResponse(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Missions_By_Name_UserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.C_Mission[] Missions_By_Name_UserResult;
        
        public Missions_By_Name_UserResponseBody() {
        }
        
        public Missions_By_Name_UserResponseBody(WS_PPE3_CLIENT.MyWS_Ref.C_Mission[] Missions_By_Name_UserResult) {
            this.Missions_By_Name_UserResult = Missions_By_Name_UserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_PersonnelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Personnel", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequestBody Body;
        
        public Insert_PersonnelRequest() {
        }
        
        public Insert_PersonnelRequest(WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_PersonnelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_MATRICULE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_NOM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string P_PRENOM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string P_RUE;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int P_CP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string P_VILLE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string P_DATE_D_EMBAUCHE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string P_email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string P_password;
        
        public Insert_PersonnelRequestBody() {
        }
        
        public Insert_PersonnelRequestBody(string P_MATRICULE, string P_NOM, string P_PRENOM, string P_RUE, int P_CP, string P_VILLE, string P_DATE_D_EMBAUCHE, string P_email, string P_password) {
            this.P_MATRICULE = P_MATRICULE;
            this.P_NOM = P_NOM;
            this.P_PRENOM = P_PRENOM;
            this.P_RUE = P_RUE;
            this.P_CP = P_CP;
            this.P_VILLE = P_VILLE;
            this.P_DATE_D_EMBAUCHE = P_DATE_D_EMBAUCHE;
            this.P_email = P_email;
            this.P_password = P_password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_PersonnelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_PersonnelResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelResponseBody Body;
        
        public Insert_PersonnelResponse() {
        }
        
        public Insert_PersonnelResponse(WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_PersonnelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Insert_PersonnelResult;
        
        public Insert_PersonnelResponseBody() {
        }
        
        public Insert_PersonnelResponseBody(string Insert_PersonnelResult) {
            this.Insert_PersonnelResult = Insert_PersonnelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Missions_By_Id_UserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Missions_By_Id_User", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequestBody Body;
        
        public Missions_By_Id_UserRequest() {
        }
        
        public Missions_By_Id_UserRequest(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Missions_By_Id_UserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_personne;
        
        public Missions_By_Id_UserRequestBody() {
        }
        
        public Missions_By_Id_UserRequestBody(string P_personne) {
            this.P_personne = P_personne;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Missions_By_Id_UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Missions_By_Id_UserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserResponseBody Body;
        
        public Missions_By_Id_UserResponse() {
        }
        
        public Missions_By_Id_UserResponse(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Missions_By_Id_UserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.C_Mission[] Missions_By_Id_UserResult;
        
        public Missions_By_Id_UserResponseBody() {
        }
        
        public Missions_By_Id_UserResponseBody(WS_PPE3_CLIENT.MyWS_Ref.C_Mission[] Missions_By_Id_UserResult) {
            this.Missions_By_Id_UserResult = Missions_By_Id_UserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_PersonnelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Personnel", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequestBody Body;
        
        public Update_PersonnelRequest() {
        }
        
        public Update_PersonnelRequest(WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_PersonnelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_MATRICULE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_NOM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string P_PRENOM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string P_RUE;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int P_CP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string P_VILLE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string P_DATE_D_EMBAUCHE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string P_email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string P_password;
        
        public Update_PersonnelRequestBody() {
        }
        
        public Update_PersonnelRequestBody(string P_MATRICULE, string P_NOM, string P_PRENOM, string P_RUE, int P_CP, string P_VILLE, string P_DATE_D_EMBAUCHE, string P_email, string P_password) {
            this.P_MATRICULE = P_MATRICULE;
            this.P_NOM = P_NOM;
            this.P_PRENOM = P_PRENOM;
            this.P_RUE = P_RUE;
            this.P_CP = P_CP;
            this.P_VILLE = P_VILLE;
            this.P_DATE_D_EMBAUCHE = P_DATE_D_EMBAUCHE;
            this.P_email = P_email;
            this.P_password = P_password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_PersonnelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_PersonnelResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelResponseBody Body;
        
        public Update_PersonnelResponse() {
        }
        
        public Update_PersonnelResponse(WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_PersonnelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Update_PersonnelResult;
        
        public Update_PersonnelResponseBody() {
        }
        
        public Update_PersonnelResponseBody(string Update_PersonnelResult) {
            this.Update_PersonnelResult = Update_PersonnelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_userRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_user", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequestBody Body;
        
        public Delete_userRequest() {
        }
        
        public Delete_userRequest(WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_userRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_user;
        
        public Delete_userRequestBody() {
        }
        
        public Delete_userRequestBody(string P_user) {
            this.P_user = P_user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_userResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_userResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.Delete_userResponseBody Body;
        
        public Delete_userResponse() {
        }
        
        public Delete_userResponse(WS_PPE3_CLIENT.MyWS_Ref.Delete_userResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_userResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Delete_userResult;
        
        public Delete_userResponseBody() {
        }
        
        public Delete_userResponseBody(string Delete_userResult) {
            this.Delete_userResult = Delete_userResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_missionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_mission", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequestBody Body;
        
        public insert_missionRequest() {
        }
        
        public insert_missionRequest(WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_missionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID_personne;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_note_de_frais;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string date_mission;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int id_per;
        
        public insert_missionRequestBody() {
        }
        
        public insert_missionRequestBody(int ID_personne, int id_note_de_frais, string nom, string date_mission, int id_per) {
            this.ID_personne = ID_personne;
            this.id_note_de_frais = id_note_de_frais;
            this.nom = nom;
            this.date_mission = date_mission;
            this.id_per = id_per;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_missionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_missionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.insert_missionResponseBody Body;
        
        public insert_missionResponse() {
        }
        
        public insert_missionResponse(WS_PPE3_CLIENT.MyWS_Ref.insert_missionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_missionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insert_missionResult;
        
        public insert_missionResponseBody() {
        }
        
        public insert_missionResponseBody(string insert_missionResult) {
            this.insert_missionResult = insert_missionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_FraisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_Frais", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequestBody Body;
        
        public insert_FraisRequest() {
        }
        
        public insert_FraisRequest(WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_FraisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DATE_DEPOT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nom;
        
        public insert_FraisRequestBody() {
        }
        
        public insert_FraisRequestBody(string DATE_DEPOT, string nom) {
            this.DATE_DEPOT = DATE_DEPOT;
            this.nom = nom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_FraisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_FraisResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.insert_FraisResponseBody Body;
        
        public insert_FraisResponse() {
        }
        
        public insert_FraisResponse(WS_PPE3_CLIENT.MyWS_Ref.insert_FraisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_FraisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insert_FraisResult;
        
        public insert_FraisResponseBody() {
        }
        
        public insert_FraisResponseBody(string insert_FraisResult) {
            this.insert_FraisResult = insert_FraisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_ligne_FraisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_ligne_Frais", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequestBody Body;
        
        public insert_ligne_FraisRequest() {
        }
        
        public insert_ligne_FraisRequest(WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_ligne_FraisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nom_frais;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int total;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int donner;
        
        public insert_ligne_FraisRequestBody() {
        }
        
        public insert_ligne_FraisRequestBody(int nom_frais, string nom, int total, int donner) {
            this.nom_frais = nom_frais;
            this.nom = nom;
            this.total = total;
            this.donner = donner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_ligne_FraisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_ligne_FraisResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisResponseBody Body;
        
        public insert_ligne_FraisResponse() {
        }
        
        public insert_ligne_FraisResponse(WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_ligne_FraisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insert_ligne_FraisResult;
        
        public insert_ligne_FraisResponseBody() {
        }
        
        public insert_ligne_FraisResponseBody(string insert_ligne_FraisResult) {
            this.insert_ligne_FraisResult = insert_ligne_FraisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class List_note_fraisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="List_note_frais", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequestBody Body;
        
        public List_note_fraisRequest() {
        }
        
        public List_note_fraisRequest(WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class List_note_fraisRequestBody {
        
        public List_note_fraisRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class List_note_fraisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="List_note_fraisResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisResponseBody Body;
        
        public List_note_fraisResponse() {
        }
        
        public List_note_fraisResponse(WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class List_note_fraisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.C_Note_Frais[] List_note_fraisResult;
        
        public List_note_fraisResponseBody() {
        }
        
        public List_note_fraisResponseBody(WS_PPE3_CLIENT.MyWS_Ref.C_Note_Frais[] List_note_fraisResult) {
            this.List_note_fraisResult = List_note_fraisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class list_ligne_fraisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="list_ligne_frais", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequestBody Body;
        
        public list_ligne_fraisRequest() {
        }
        
        public list_ligne_fraisRequest(WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class list_ligne_fraisRequestBody {
        
        public list_ligne_fraisRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class list_ligne_fraisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="list_ligne_fraisResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisResponseBody Body;
        
        public list_ligne_fraisResponse() {
        }
        
        public list_ligne_fraisResponse(WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class list_ligne_fraisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_PPE3_CLIENT.MyWS_Ref.C_Liste_Frais[] list_ligne_fraisResult;
        
        public list_ligne_fraisResponseBody() {
        }
        
        public list_ligne_fraisResponseBody(WS_PPE3_CLIENT.MyWS_Ref.C_Liste_Frais[] list_ligne_fraisResult) {
            this.list_ligne_fraisResult = list_ligne_fraisResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWSSoapChannel : WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWSSoapClient : System.ServiceModel.ClientBase<WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap>, WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap {
        
        public MyWSSoapClient() {
        }
        
        public MyWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Liste_Mission(WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequest request) {
            return base.Channel.Liste_Mission(request);
        }
        
        public WS_PPE3_CLIENT.MyWS_Ref.C_Mission[] Liste_Mission() {
            WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequestBody();
            WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Liste_Mission(inValue);
            return retVal.Body.Liste_MissionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Liste_MissionAsync(WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequest request) {
            return base.Channel.Liste_MissionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionResponse> Liste_MissionAsync() {
            WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Liste_MissionRequestBody();
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Liste_MissionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Liste_Personnel(WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequest request) {
            return base.Channel.Liste_Personnel(request);
        }
        
        public WS_PPE3_CLIENT.MyWS_Ref.C_PERSONNEL[] Liste_Personnel() {
            WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequestBody();
            WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Liste_Personnel(inValue);
            return retVal.Body.Liste_PersonnelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Liste_PersonnelAsync(WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequest request) {
            return base.Channel.Liste_PersonnelAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelResponse> Liste_PersonnelAsync() {
            WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Liste_PersonnelRequestBody();
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Liste_PersonnelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Missions_By_Name_User(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequest request) {
            return base.Channel.Missions_By_Name_User(request);
        }
        
        public WS_PPE3_CLIENT.MyWS_Ref.C_Mission[] Missions_By_Name_User(string P_NOM) {
            WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequestBody();
            inValue.Body.P_NOM = P_NOM;
            WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Missions_By_Name_User(inValue);
            return retVal.Body.Missions_By_Name_UserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Missions_By_Name_UserAsync(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequest request) {
            return base.Channel.Missions_By_Name_UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserResponse> Missions_By_Name_UserAsync(string P_NOM) {
            WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Name_UserRequestBody();
            inValue.Body.P_NOM = P_NOM;
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Missions_By_Name_UserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Insert_Personnel(WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequest request) {
            return base.Channel.Insert_Personnel(request);
        }
        
        public string Insert_Personnel(string P_MATRICULE, string P_NOM, string P_PRENOM, string P_RUE, int P_CP, string P_VILLE, string P_DATE_D_EMBAUCHE, string P_email, string P_password) {
            WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequestBody();
            inValue.Body.P_MATRICULE = P_MATRICULE;
            inValue.Body.P_NOM = P_NOM;
            inValue.Body.P_PRENOM = P_PRENOM;
            inValue.Body.P_RUE = P_RUE;
            inValue.Body.P_CP = P_CP;
            inValue.Body.P_VILLE = P_VILLE;
            inValue.Body.P_DATE_D_EMBAUCHE = P_DATE_D_EMBAUCHE;
            inValue.Body.P_email = P_email;
            inValue.Body.P_password = P_password;
            WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Insert_Personnel(inValue);
            return retVal.Body.Insert_PersonnelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Insert_PersonnelAsync(WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequest request) {
            return base.Channel.Insert_PersonnelAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelResponse> Insert_PersonnelAsync(string P_MATRICULE, string P_NOM, string P_PRENOM, string P_RUE, int P_CP, string P_VILLE, string P_DATE_D_EMBAUCHE, string P_email, string P_password) {
            WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Insert_PersonnelRequestBody();
            inValue.Body.P_MATRICULE = P_MATRICULE;
            inValue.Body.P_NOM = P_NOM;
            inValue.Body.P_PRENOM = P_PRENOM;
            inValue.Body.P_RUE = P_RUE;
            inValue.Body.P_CP = P_CP;
            inValue.Body.P_VILLE = P_VILLE;
            inValue.Body.P_DATE_D_EMBAUCHE = P_DATE_D_EMBAUCHE;
            inValue.Body.P_email = P_email;
            inValue.Body.P_password = P_password;
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Insert_PersonnelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Missions_By_Id_User(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequest request) {
            return base.Channel.Missions_By_Id_User(request);
        }
        
        public WS_PPE3_CLIENT.MyWS_Ref.C_Mission[] Missions_By_Id_User(string P_personne) {
            WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequestBody();
            inValue.Body.P_personne = P_personne;
            WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Missions_By_Id_User(inValue);
            return retVal.Body.Missions_By_Id_UserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Missions_By_Id_UserAsync(WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequest request) {
            return base.Channel.Missions_By_Id_UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserResponse> Missions_By_Id_UserAsync(string P_personne) {
            WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Missions_By_Id_UserRequestBody();
            inValue.Body.P_personne = P_personne;
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Missions_By_Id_UserAsync(inValue);
        }
        
        public bool Je_Me_Connecte() {
            return base.Channel.Je_Me_Connecte();
        }
        
        public System.Threading.Tasks.Task<bool> Je_Me_ConnecteAsync() {
            return base.Channel.Je_Me_ConnecteAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Update_Personnel(WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequest request) {
            return base.Channel.Update_Personnel(request);
        }
        
        public string Update_Personnel(string P_MATRICULE, string P_NOM, string P_PRENOM, string P_RUE, int P_CP, string P_VILLE, string P_DATE_D_EMBAUCHE, string P_email, string P_password) {
            WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequestBody();
            inValue.Body.P_MATRICULE = P_MATRICULE;
            inValue.Body.P_NOM = P_NOM;
            inValue.Body.P_PRENOM = P_PRENOM;
            inValue.Body.P_RUE = P_RUE;
            inValue.Body.P_CP = P_CP;
            inValue.Body.P_VILLE = P_VILLE;
            inValue.Body.P_DATE_D_EMBAUCHE = P_DATE_D_EMBAUCHE;
            inValue.Body.P_email = P_email;
            inValue.Body.P_password = P_password;
            WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Update_Personnel(inValue);
            return retVal.Body.Update_PersonnelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Update_PersonnelAsync(WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequest request) {
            return base.Channel.Update_PersonnelAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelResponse> Update_PersonnelAsync(string P_MATRICULE, string P_NOM, string P_PRENOM, string P_RUE, int P_CP, string P_VILLE, string P_DATE_D_EMBAUCHE, string P_email, string P_password) {
            WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Update_PersonnelRequestBody();
            inValue.Body.P_MATRICULE = P_MATRICULE;
            inValue.Body.P_NOM = P_NOM;
            inValue.Body.P_PRENOM = P_PRENOM;
            inValue.Body.P_RUE = P_RUE;
            inValue.Body.P_CP = P_CP;
            inValue.Body.P_VILLE = P_VILLE;
            inValue.Body.P_DATE_D_EMBAUCHE = P_DATE_D_EMBAUCHE;
            inValue.Body.P_email = P_email;
            inValue.Body.P_password = P_password;
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Update_PersonnelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.Delete_userResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Delete_user(WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequest request) {
            return base.Channel.Delete_user(request);
        }
        
        public string Delete_user(string P_user) {
            WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequestBody();
            inValue.Body.P_user = P_user;
            WS_PPE3_CLIENT.MyWS_Ref.Delete_userResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Delete_user(inValue);
            return retVal.Body.Delete_userResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Delete_userResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.Delete_userAsync(WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequest request) {
            return base.Channel.Delete_userAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.Delete_userResponse> Delete_userAsync(string P_user) {
            WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.Delete_userRequestBody();
            inValue.Body.P_user = P_user;
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).Delete_userAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.insert_missionResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.insert_mission(WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequest request) {
            return base.Channel.insert_mission(request);
        }
        
        public string insert_mission(int ID_personne, int id_note_de_frais, string nom, string date_mission, int id_per) {
            WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequestBody();
            inValue.Body.ID_personne = ID_personne;
            inValue.Body.id_note_de_frais = id_note_de_frais;
            inValue.Body.nom = nom;
            inValue.Body.date_mission = date_mission;
            inValue.Body.id_per = id_per;
            WS_PPE3_CLIENT.MyWS_Ref.insert_missionResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).insert_mission(inValue);
            return retVal.Body.insert_missionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.insert_missionResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.insert_missionAsync(WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequest request) {
            return base.Channel.insert_missionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.insert_missionResponse> insert_missionAsync(int ID_personne, int id_note_de_frais, string nom, string date_mission, int id_per) {
            WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.insert_missionRequestBody();
            inValue.Body.ID_personne = ID_personne;
            inValue.Body.id_note_de_frais = id_note_de_frais;
            inValue.Body.nom = nom;
            inValue.Body.date_mission = date_mission;
            inValue.Body.id_per = id_per;
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).insert_missionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.insert_FraisResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.insert_Frais(WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequest request) {
            return base.Channel.insert_Frais(request);
        }
        
        public string insert_Frais(string DATE_DEPOT, string nom) {
            WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequestBody();
            inValue.Body.DATE_DEPOT = DATE_DEPOT;
            inValue.Body.nom = nom;
            WS_PPE3_CLIENT.MyWS_Ref.insert_FraisResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).insert_Frais(inValue);
            return retVal.Body.insert_FraisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.insert_FraisResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.insert_FraisAsync(WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequest request) {
            return base.Channel.insert_FraisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.insert_FraisResponse> insert_FraisAsync(string DATE_DEPOT, string nom) {
            WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.insert_FraisRequestBody();
            inValue.Body.DATE_DEPOT = DATE_DEPOT;
            inValue.Body.nom = nom;
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).insert_FraisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.insert_ligne_Frais(WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequest request) {
            return base.Channel.insert_ligne_Frais(request);
        }
        
        public string insert_ligne_Frais(int nom_frais, string nom, int total, int donner) {
            WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequestBody();
            inValue.Body.nom_frais = nom_frais;
            inValue.Body.nom = nom;
            inValue.Body.total = total;
            inValue.Body.donner = donner;
            WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).insert_ligne_Frais(inValue);
            return retVal.Body.insert_ligne_FraisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.insert_ligne_FraisAsync(WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequest request) {
            return base.Channel.insert_ligne_FraisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisResponse> insert_ligne_FraisAsync(int nom_frais, string nom, int total, int donner) {
            WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.insert_ligne_FraisRequestBody();
            inValue.Body.nom_frais = nom_frais;
            inValue.Body.nom = nom;
            inValue.Body.total = total;
            inValue.Body.donner = donner;
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).insert_ligne_FraisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.List_note_frais(WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequest request) {
            return base.Channel.List_note_frais(request);
        }
        
        public WS_PPE3_CLIENT.MyWS_Ref.C_Note_Frais[] List_note_frais() {
            WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequestBody();
            WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).List_note_frais(inValue);
            return retVal.Body.List_note_fraisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.List_note_fraisAsync(WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequest request) {
            return base.Channel.List_note_fraisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisResponse> List_note_fraisAsync() {
            WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.List_note_fraisRequestBody();
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).List_note_fraisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisResponse WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.list_ligne_frais(WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequest request) {
            return base.Channel.list_ligne_frais(request);
        }
        
        public WS_PPE3_CLIENT.MyWS_Ref.C_Liste_Frais[] list_ligne_frais() {
            WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequestBody();
            WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisResponse retVal = ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).list_ligne_frais(inValue);
            return retVal.Body.list_ligne_fraisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisResponse> WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap.list_ligne_fraisAsync(WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequest request) {
            return base.Channel.list_ligne_fraisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisResponse> list_ligne_fraisAsync() {
            WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequest inValue = new WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequest();
            inValue.Body = new WS_PPE3_CLIENT.MyWS_Ref.list_ligne_fraisRequestBody();
            return ((WS_PPE3_CLIENT.MyWS_Ref.MyWSSoap)(this)).list_ligne_fraisAsync(inValue);
        }
    }
}
